version: '3'

services:
  metabase:
    image: metabase/metabase
    container_name: my_metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: your_database_name
      MB_DB_PORT: 5432
      MB_DB_USER: your_username
      MB_DB_PASS: your_password
      MB_DB_HOST: your_host
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
