version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    env_file: ./postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my_pgadmin
    env_file: ./postgres.env
    ports:
      - "5050:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
